import 'package:envied/envied.dart';

part 'env.g.dart';

/// Compile-time secrets, generated by envied from the project-root `.env` file.
///
/// Fields are `optional`, so an empty/absent value resolves to `null` and the
/// project still builds out of the box. Provide real values in `.env` (or via
/// CI) — never commit real secrets.
@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'SENTRY_DSN', obfuscate: false, optional: true)
  static const String? sentryDsn = _Env.sentryDsn;

  @EnviedField(varName: 'API_KEY', obfuscate: false, optional: true)
  static const String? apiKey = _Env.apiKey;
}
